-- ============================================================
-- Migration 018: Sync NEW database schema to match OLD database
-- Run this on the NEW Supabase project (ebdoxleodzmvmfykakig)
-- ============================================================
-- Generated by schema comparison on June 2026
-- OLD: zmucqoeihukhmotzxrgs  (source/reference)
-- NEW: ebdoxleodzmvmfykakig  (target to update)
-- ============================================================

-- ─────────────────────────────────────────────────────────────
-- SECTION 1: ADD MISSING COLUMNS TO EXISTING TABLES
-- ─────────────────────────────────────────────────────────────

-- 1. activity_logs → add ip_address
ALTER TABLE public.activity_logs
  ADD COLUMN IF NOT EXISTS ip_address VARCHAR;

-- 2. audit_logs → add missing columns (old schema used resource_* naming)
ALTER TABLE public.audit_logs
  ADD COLUMN IF NOT EXISTS resource_type   VARCHAR,
  ADD COLUMN IF NOT EXISTS resource_id     UUID,
  ADD COLUMN IF NOT EXISTS resource_name   VARCHAR,
  ADD COLUMN IF NOT EXISTS old_values      JSONB,
  ADD COLUMN IF NOT EXISTS new_values      JSONB,
  ADD COLUMN IF NOT EXISTS status          VARCHAR DEFAULT 'success',
  ADD COLUMN IF NOT EXISTS error_message   TEXT;

-- Sync entity_* → resource_* for backward compatibility
UPDATE public.audit_logs SET
  resource_type = entity_type,
  resource_id   = entity_id
WHERE resource_type IS NULL AND entity_type IS NOT NULL;

-- 3. employee_leave_balance → old used different column names
ALTER TABLE public.employee_leave_balance
  ADD COLUMN IF NOT EXISTS total_days     INTEGER,
  ADD COLUMN IF NOT EXISTS used_days      INTEGER,
  ADD COLUMN IF NOT EXISTS pending_days   INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS remaining_days INTEGER,
  ADD COLUMN IF NOT EXISTS last_updated   TIMESTAMP DEFAULT NOW();

-- Sync new→old column names
UPDATE public.employee_leave_balance SET
  total_days     = days_allocated,
  used_days      = days_used,
  remaining_days = days_remaining,
  last_updated   = updated_at
WHERE total_days IS NULL;

-- 4. employee_leave_deduction_tracking → old had year/total_deducted_days
ALTER TABLE public.employee_leave_deduction_tracking
  ADD COLUMN IF NOT EXISTS year               INTEGER,
  ADD COLUMN IF NOT EXISTS total_deducted_days NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS updated_at         TIMESTAMP DEFAULT NOW();

-- Sync deducted days from new columns
UPDATE public.employee_leave_deduction_tracking SET
  total_deducted_days = days_deducted,
  updated_at          = created_at
WHERE total_deducted_days IS NULL;

-- 5. employees → add user_id
ALTER TABLE public.employees
  ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES public.users(id) ON DELETE SET NULL;

-- 6. grade_benefits → add missing columns
ALTER TABLE public.grade_benefits
  ADD COLUMN IF NOT EXISTS company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS value_type VARCHAR DEFAULT 'fixed',
  ADD COLUMN IF NOT EXISTS currency   VARCHAR DEFAULT 'AED',
  ADD COLUMN IF NOT EXISTS active     BOOLEAN DEFAULT TRUE;

-- Populate company_id for grade_benefits from parent grade
UPDATE public.grade_benefits gb
SET company_id = eg.company_id
FROM public.employee_grades eg
WHERE gb.grade_id = eg.id
  AND gb.company_id IS NULL;

-- 7. grade_leave_config → add missing columns
ALTER TABLE public.grade_leave_config
  ADD COLUMN IF NOT EXISTS company_id                  UUID REFERENCES public.companies(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS days_per_year               INTEGER,
  ADD COLUMN IF NOT EXISTS carry_forward_days          INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS carry_forward_expiry_months INTEGER DEFAULT 3,
  ADD COLUMN IF NOT EXISTS year                        INTEGER,
  ADD COLUMN IF NOT EXISTS updated_at                  TIMESTAMP DEFAULT NOW();

-- Sync days_allocated → days_per_year
UPDATE public.grade_leave_config SET days_per_year = days_allocated
WHERE days_per_year IS NULL AND days_allocated IS NOT NULL;

-- Populate company_id for grade_leave_config
UPDATE public.grade_leave_config glc
SET company_id = eg.company_id
FROM public.employee_grades eg
WHERE glc.grade_id = eg.id
  AND glc.company_id IS NULL;

-- 8. leave_approvers → add missing columns
ALTER TABLE public.leave_approvers
  ADD COLUMN IF NOT EXISTS approval_level INTEGER DEFAULT 1,
  ADD COLUMN IF NOT EXISTS active         BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS updated_at     TIMESTAMP DEFAULT NOW();

-- 9. leave_types → add updated_at
ALTER TABLE public.leave_types
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW();

-- 10. leaves → add approval workflow columns
ALTER TABLE public.leaves
  ADD COLUMN IF NOT EXISTS requested_by       UUID,
  ADD COLUMN IF NOT EXISTS approved_by        UUID,
  ADD COLUMN IF NOT EXISTS approval_date      TIMESTAMP,
  ADD COLUMN IF NOT EXISTS manager_comments   TEXT,
  ADD COLUMN IF NOT EXISTS approval_status    VARCHAR,
  ADD COLUMN IF NOT EXISTS rejection_reason   TEXT,
  ADD COLUMN IF NOT EXISTS is_comp_off        BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS comp_off_request_id UUID,
  ADD COLUMN IF NOT EXISTS company_id         UUID REFERENCES public.companies(id) ON DELETE CASCADE;

-- Sync status → approval_status for approved/rejected records
UPDATE public.leaves SET
  approval_status = status
WHERE approval_status IS NULL AND status IN ('approved','rejected','pending');

-- Populate leaves.company_id from employee
UPDATE public.leaves l
SET company_id = e.company_id
FROM public.employees e
WHERE l.employee_id = e.id
  AND l.company_id IS NULL;

-- 11. modules → add is_system and updated_at
ALTER TABLE public.modules
  ADD COLUMN IF NOT EXISTS is_system  BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW();

-- 12. payroll → add leave deduction columns
ALTER TABLE public.payroll
  ADD COLUMN IF NOT EXISTS leave_deduction_days   NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS leave_deduction_amount NUMERIC DEFAULT 0;

-- 13. user_companies → add assigned_at
ALTER TABLE public.user_companies
  ADD COLUMN IF NOT EXISTS assigned_at TIMESTAMP;

UPDATE public.user_companies
SET assigned_at = created_at
WHERE assigned_at IS NULL;

-- ─────────────────────────────────────────────────────────────
-- SECTION 2: CREATE MISSING TABLES
-- ─────────────────────────────────────────────────────────────

-- 14. audit_log_policies table
CREATE TABLE IF NOT EXISTS public.audit_log_policies (
  id               UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  company_id       UUID REFERENCES public.companies(id) ON DELETE CASCADE,
  resource_type    VARCHAR,
  retention_days   INTEGER DEFAULT 90,
  archive_enabled  BOOLEAN DEFAULT FALSE,
  created_at       TIMESTAMP DEFAULT NOW(),
  updated_at       TIMESTAMP DEFAULT NOW()
);

ALTER TABLE public.audit_log_policies ENABLE ROW LEVEL SECURITY;

CREATE POLICY "audit_log_policies_company" ON public.audit_log_policies
  FOR ALL USING (
    company_id IN (SELECT company_id FROM public.users WHERE id = auth.uid())
  );

-- ─────────────────────────────────────────────────────────────
-- SECTION 3: CREATE MISSING VIEWS
-- ─────────────────────────────────────────────────────────────

-- 15. audit_log_search view
DROP VIEW IF EXISTS public.audit_log_search;
CREATE OR REPLACE VIEW public.audit_log_search AS
SELECT
  al.id,
  al.user_id,
  CONCAT(u.first_name, ' ', u.last_name) AS user_name,
  al.company_id,
  c.name                                  AS company_name,
  al.action,
  COALESCE(al.resource_type, al.entity_type)  AS resource_type,
  COALESCE(al.resource_id,   al.entity_id)    AS resource_id,
  al.resource_name,
  al.status,
  al.created_at,
  al.ip_address,
  (al.old_values IS NOT NULL OR al.new_values IS NOT NULL OR al.changes IS NOT NULL) AS has_changes
FROM public.audit_logs al
LEFT JOIN public.users     u ON al.user_id    = u.id
LEFT JOIN public.companies c ON al.company_id = c.id;

-- 16. leave_dashboard view
DROP VIEW IF EXISTS public.leave_dashboard;
CREATE OR REPLACE VIEW public.leave_dashboard AS
SELECT
  e.id                                    AS employee_id,
  CONCAT(e.first_name, ' ', e.last_name) AS employee_name,
  e.company_id,
  lt.name                                 AS leave_type,
  elb.total_days,
  elb.used_days,
  COALESCE(elb.pending_days, 0)          AS pending_days,
  elb.remaining_days,
  elb.year,
  CASE
    WHEN COALESCE(elb.total_days, 0) = 0 THEN 0
    ELSE ROUND((COALESCE(elb.used_days, 0)::NUMERIC / elb.total_days) * 100, 1)
  END AS usage_percentage
FROM public.employees e
JOIN public.employee_leave_balance elb ON elb.employee_id = e.id
JOIN public.leave_types lt ON lt.id = elb.leave_type_id;

-- ─────────────────────────────────────────────────────────────
-- SECTION 4: INDEXES FOR PERFORMANCE
-- ─────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_leaves_company_id      ON public.leaves(company_id);
CREATE INDEX IF NOT EXISTS idx_leaves_approval_status ON public.leaves(approval_status);
CREATE INDEX IF NOT EXISTS idx_employees_user_id      ON public.employees(user_id);
CREATE INDEX IF NOT EXISTS idx_grade_benefits_company ON public.grade_benefits(company_id);
CREATE INDEX IF NOT EXISTS idx_grade_leave_company    ON public.grade_leave_config(company_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_resource    ON public.audit_logs(resource_type, resource_id);

-- ─────────────────────────────────────────────────────────────
-- SECTION 5: VERIFICATION
-- ─────────────────────────────────────────────────────────────
SELECT
  table_name,
  COUNT(*) AS column_count
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name NOT IN ('schema_migrations')
GROUP BY table_name
ORDER BY table_name;
